### ISSUE TITLE
casual --information should contain starttime

### ISSUE THREAD

**Issue by ahhud** [casualcore/casual#132]
It would be great if the state contains starttime for domain.
When troubleshooting a domain it is important to know if the domain have been restarted after some interresting log entries to be able to know if the domain state still is relevant.

**Comment by lazan** [comment]
As files do it...

* created
* updated

**Comment by ahhud** [comment]
In this issue we only address initial requirement on created timepoint.
To implement _updated_ it requires added timepoint in configuration state that keep track of timepoints for the explicit act of reconfiguration.
It would be possible to detect latest spawned server or executable, but that would not be the same as latest _updated_.
Pushing eventual _updated_ to 1.7 or later.
