### ISSUE TITLE
unittest robustness

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#15]
```
[ RUN      ] domain_manager.kill_internal_pending__expect_restart
/git/casual/casual/middleware/domain/unittest/source/manager/test_manager.cpp:968: Failure
Value of: event.alias == "casual-domain-pending-message"
  Actual: false
Expected: true
event: { type: event_process_spawn, correlation: a14aff25435d4ca89a7b668202335bab, payload: execution: 05738335dc8544209f201e7e2ff350e3, process: { pid: nil, ipc: nil}, alias: casual-domain-discovery, path: /git/casual/casual/middleware/domain/bin/casual-domain-discovery, pids: [2991]}
[  FAILED  ] domain_manager.kill_internal_pending__expect_restart (23 ms)

```

Hangs: 
* `casual_queue_forward.advertise_service__enqueue_2_message__expect_forward_on_first__and_service_lookup_discard_on_shutdown)`
* `casual_queue_forward.enqueue_c1__expect_queue_forward_to_c2_c3_c4`
`

```
[ RUN      ] gateway_manager.async_5_remote1_call__expect_pending_metric
/git/casual/casual/middleware/gateway/unittest/source/test_manager.cpp:822: Failure
Value of: metrics.size() == count
  Actual: false
Expected: true
metrics: [{ service: a, parent: , type: concurrent, process: { pid: 4428, ipc: 42caa509c7cb47ad96b2910faaba5fea}, correlation: 195823daff8a47dabfb1ff9e133dfd97, execution: 623256a2689242ad8fe805e7d222a960, trid: , start: 1649712477252896801, end: 1649712477261232981, pending: 0, code: [xatmi:OK]}, { service: a, parent: , type: concurrent, process: { pid: 4428, ipc: 42caa509c7cb47ad96b2910faaba5fea}, correlation: 3e62baad0cd54da98095ac7d11312ac1, execution: 623256a2689242ad8fe805e7d222a960, trid: , start: 1649712477250444243, end: 1649712477254257318, pending: 0, code: [xatmi:OK]}, { service: a, parent: , type: concurrent, process: { pid: 4428, ipc: 42caa509c7cb47ad96b2910faaba5fea}, correlation: 574e9c8705814f19b14bab85443ced3b, execution: 623256a2689242ad8fe805e7d222a960, trid: , start: 1649712477251766372, end: 1649712477257280641, pending: 0, code: [xatmi:OK]}, { service: a, parent: , type: concurrent, process: { pid: 4428, ipc: 42caa509c7cb47ad96b2910faaba5fea}, correlation: e877ac3f532241a798d74e1b312e7546, execution: 623256a2689242ad8fe805e7d222a960, trid: , start: 1649712477252389345, end: 1649712477259251042, pending: 0, code: [xatmi:OK]}]
[  FAILED  ] gateway_manager.async_5_remote1_call__expect_pending_metric (227 ms)

[ RUN      ] casual_queue_forward.configuration_get
/git/casual/casual/middleware/queue/unittest/source/test_forward.cpp:206: Failure
Value of: origin.queue == model.queue
  Actual: false
Expected: true
origin.queue: { groups: [{ alias: a, queuebase: :memory:, note: alias-a, queues: [{ name: a1, retry: { count: 3, delay: 0}, note: queue a1}, { name: a2, retry: { count: 3, delay: 0}, note: }, { name: a3, retry: { count: 3, delay: 0}, note: }, { name: a4, retry: { count: 3, delay: 0}, note: }]}, { alias: b, queuebase: :memory:, note: , queues: [{ name: b1, retry: { count: 3, delay: 0}, note: }, { name: b2, retry: { count: 3, delay: 0}, note: }, { name: b3, retry: { count: 3, delay: 0}, note: }, { name: b4, retry: { count: 3, delay: 0}, note: }]}, { alias: c, queuebase: :memory:, note: , queues: [{ name: c1, retry: { count: 3, delay: 0}, note: }, { name: c2, retry: { count: 3, delay: 0}, note: }, { name: c3, retry: { count: 3, delay: 0}, note: }, { name: c4, retry: { count: 3, delay: 0}, note: }]}], forward: { groups: [{ alias: forward-group-1, services: [{ alias: foo, source: a1, instances: 4, note: some note..., target: { service: queue/unittest/service}, reply: { queue: b1, delay: 0}}, { alias: bar, source: a2, instances: 4, note: , target: { service: queue/unittest/service}, reply: { queue: b2, delay: 0}}, { alias: a3, source: a3, instances: 1, note: , target: { service: queue/unittest/service}, reply: { queue: b3, delay: 0}}, { alias: x1, source: x1, instances: 4, note: , target: { service: queue/unittest/service}, reply: { queue: b1, delay: 0}}], queues: [{ alias: a4, source: a4, instances: 2, note: , target: { queue: b4, delay: 10000000}}, { alias: c1, source: c1, instances: 1, note: , target: { queue: c2, delay: 0}}, { alias: c2, source: c2, instances: 1, note: , target: { queue: c3, delay: 0}}, { alias: c3, source: c3, instances: 1, note: , target: { queue: c4, delay: 0}}], note: }]}, note: some note...}
model.queue: { groups: [], forward: { groups: []}, note: }
[  FAILED  ] casual_queue_forward.configuration_get (141 ms)


```

- [ ] gateway_manager.advertise_b_to_B__call_b_via_A__simulate_A_get_the_same_call_message_again__loop_between_gateways__expect_error_reply

**Comment by OlofGullnas** [comment]
I did a build of feature/1.6/main commit  28a78e6e39872bb87ce85c461f4319b0e23d95d0 ( 1.6.0-beta.22) with casual-make --debug and then ran the tests.

The following step failed(1):
[ RUN      ] common_communication_ipc.send_multiplex_to_inbound__fill_the_ipc__and_cache_the_rest__                  sink_the_inbounds__expect_callback_invocation__and_empty_state_when_done
/export/home/guo/casual/middleware/common/unittest/source/communication/test_ipc.cpp:395: Failure
Value of: ! coordinator.empty()
  Actual: false
Expected: true
/export/home/guo/casual/middleware/common/unittest/source/communication/test_ipc.cpp:398: Failure
Value of: count > 0
  Actual: false
Expected: true
[  FAILED  ] common_communication_ipc.send_multiplex_to_inbound__fill_the_ipc__and_cache_the_rest__                  sink_the_inbounds__expect_callback_invocation__and_empty_state_when_done (31 ms)

(This failure seems to be reproducible in my enviroment. Occurred every time I tried to run only this test.)

Disabled that test with GTEST_FILTER and re-executed: now hangs in (2):
[ RUN      ] gateway_manager.advertise_b_to_B__call_b_via_A__simulate_A_get_the_same_call_message_again__loop_between_gateways__expect_error_reply

Did a kill of prcess executing .../gateway/bin/casual-gateway-outbound-group
 and test proceeded to the end without errors.

When reexecuting the test suite it ran to completion without the hang (2).
To not hang in this test seems to be rare. Did not hang 1 time out of 5 runs, and the hang was on the same test each time.

On the 6:th run two other tests FAILED:
[ RUN      ] transaction_manager.begin_commit_transaction__1_resources_involved__environment_open_info__XAER_NOTA___expect__TX_OK
unknown file: Failure
C++ exception with description "lookup: { service: .casual/transaction/state, correlation: nil, reply: }: TPENOENT" thrown in the test body.
[  FAILED  ] transaction_manager.begin_commit_transaction__1_resources_involved__environment_open_info__XAER_NOTA___expect__TX_OK (123 ms)
[ RUN      ] transaction_manager.begin_rollback_transaction__1_resources_involved__expect_XA_OK
/export/home/guo/casual/middleware/transaction/unittest/source/test_manager.cpp:596: Failure
Value of: local::begin() == common::code::tx::ok
  Actual: false
Expected: true
[  FAILED  ] transaction_manager.begin_rollback_transaction__1_resources_involved__expect_XA_OK (129 ms)

(This seems to be a rare failure.)

On next re-execution theese tests worked OK but the hang occurred.

**Comment by lazan** [comment]
Thank you. I'll try to reason around the test-cases to see if I can understand the failed semantics in the unittests, or possible some bug in casual.
You do run with _debug_ ?

**Comment by OlofGullnas** [comment]
Yes, I build with --debug.  Obviously should not affect how things work :-), but may cause different timing.

I tried runnig only the test case that hangs most times and with CASUAL_LOG="(.*|error|warning|information)". It was more difficult to get the hang, but after a number of tries it hang. The last 50 lines of casual.log contain the attached.
[tail-casual.log](https://github.com/casualcore/casual/files/9714017/tail-casual.log)

The pid 83987 is a process executing gateway/bin/casual-gateway-outbound-group. a kill of that proceess makes execution proceed. Is it not reacting as it should to its child exiting?

**Comment by OlofGullnas** [comment]
I did a build of 1.6/main commit  06f799327c565f05373c00fffbbbe15729cdebb7 (=beta.35). I built with --debug as I usually do, and with g++-11. 
Still fails/hangs, and in new places. When I run the test it hangs in the step:
  service_forward_cache.forward_call_TPNOTRAN
  
```
And it seems to happen on every run. When it hangs the "existing" involved processes seems to be:
guo       21859    903  0 11:44 pts/0    00:00:01 python3 /export/home/guo/casual/../casual-make/source/casual-make --debug test
guo       21903  21859  0 11:44 pts/0    00:00:00 python3 /export/home/guo/casual/../casual-make/source/casual-make --debug test
guo       21911  21859  0 11:44 pts/0    00:00:00 /export/home/guo/casual/middleware/service/unittest/bin/test-casual-service --gtest_color=yes
guo       21912  21911  0 11:44 pts/0    00:00:00 /export/home/guo/casual/middleware/domain/bin/casual-domain-manager --bare true --event-pid 21911 --event-ipc 74453b96af934331ac2c0ead84c6a375 --event-id 57224114193c4cd697cd40662b9b68dd --configuration-files /tmp/unittest-ea12a358776f4ac4af1bc3ed0b03742b.yaml
guo       21913  21912  0 11:44 pts/0    00:00:00 /export/home/guo/casual/middleware/domain/bin/casual-domain-discovery
guo       22955   1004  0 12:00 pts/1    00:00:00 grep --color=auto casual
```

A kill command on "casual-domain-discovery" just results in it being starterd again. To get out of the hang I have to kill more processes. 
I did a run of only this test with CASUAL_LOG=.* 
Will try to attach log...

[forward_call_TPNOTRAN_casual.log](https://github.com/casualcore/casual/files/10217280/forward_call_TPNOTRAN_casual.log)

Om jag gör kill på pid 21913 så startar den om. om jag gör kill på casual-domain-discovery och domain-manager så blir domain manager 'defunct'

. Om jag även gör kill på bin/test-casual-service så får jag:
```
[ RUN      ] service_forward_cache.forward_call_TPNOTRAN
unknown file: Failure
C++ exception with description "raise signal: terminate" thrown in the test body.
[  FAILED  ] service_forward_cache.forward_call_TPNOTRAN (2399740 ms)
[----------] 1 test from service_forward_cache (2399740 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (2399742 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] service_forward_cache.forward_call_TPNOTRAN

 1 FAILED TEST
aborting due to errors
```

**Comment by OlofGullnas** [comment]
I did a build of feature/1.6/main (commit 7698cd705bd644ecd0407fc2d75d6e6525176c9b, tagged with  1.6.0-beta.43).


casual-make --debug test fails in a number of tests on my single core Linux virtual machine. The failing tests seems to be in  transaction_manager.* test suite. The number of tests that fail varies with each run. One time it did run to completion, but most times 6-11 test steps fail. Failures in this suite is a "recent" change. in behaviour Tests did not use to fail here.   

```
[ RUN      ] transaction_manager.begin_transaction
unknown file: Failure
C++ exception with description "lookup: { service: .casual/transaction/state, correlation: nil, reply: }: TPENOENT" thrown in the test body.
[  FAILED  ] transaction_manager.begin_transaction (115 ms)
[ RUN      ] transaction_manager.commit_transaction__expect_ok__no_resource_roundtrips
/export/home/guo/casual/middleware/transaction/unittest/source/test_manager.cpp:383: Failure
Value of: local::begin() == common::code::tx::ok
  Actual: false
Expected: true
[  FAILED  ] transaction_manager.commit_transaction__expect_ok__no_resource_roundtrips (115 ms)
[ RUN      ] transaction_manager.begin_commit_transaction__1_resources_involved__expect_one_phase_commit_optimization
unknown file: Failure
C++ exception with description "lookup: { service: .casual/transaction/state, correlation: nil, reply: }: TPENOENT" thrown in the test body.
[  FAILED  ] transaction_manager.begin_commit_transaction__1_resources_involved__expect_one_phase_commit_optimization (113 ms)
[ RUN      ] transaction_manager.begin_commit_transaction__1_resources_involved__2_times___expect_one_phase_commit_optimization
/export/home/guo/casual/middleware/transaction/unittest/source/test_manager.cpp:439: Failure
Value of: local::begin() == common::code::tx::ok
  Actual: false
Expected: true
[  FAILED  ] transaction_manager.begin_commit_transaction__1_resources_involved__2_times___expect_one_phase_commit_optimization (116 ms)
[ RUN      ] transaction_manager.begin_commit_transaction__1_resources_involved__xa_XA_RBDEADLOCK___expect__TX_HAZARD
unknown file: Failure
C++ exception with description "lookup: { service: .casual/transaction/state, correlation: nil, reply: }: TPENOENT" thrown in the test body.
[  FAILED  ] transaction_manager.begin_commit_transaction__1_resources_involved__xa_XA_RBDEADLOCK___expect__TX_HAZARD (113 ms)
[ RUN      ] transaction_manager.no_transaction__1_resources_involved__XAER_NOTA___expect__TX_OK
/export/home/guo/casual/middleware/transaction/unittest/source/test_manager.cpp:537: Failure
Value of: local::begin() == common::code::tx::ok
  Actual: false
Expected: true
[  FAILED  ] transaction_manager.no_transaction__1_resources_involved__XAER_NOTA___expect__TX_OK (116 ms)
[ RUN      ] transaction_manager.begin_commit_transaction__1_resources_involved__environment_open_info__XAER_NOTA___expect__TX_OK
unknown file: Failure
C++ exception with description "lookup: { service: .casual/transaction/state, correlation: nil, reply: }: TPENOENT" thrown in the test body.
[  FAILED  ] transaction_manager.begin_commit_transaction__1_resources_involved__environment_open_info__XAER_NOTA___expect__TX_OK (117 ms)
[ RUN      ] transaction_manager.begin_rollback_transaction__1_resources_involved__expect_XA_OK
/export/home/guo/casual/middleware/transaction/unittest/source/test_manager.cpp:592: Failure
Value of: local::begin() == common::code::tx::ok
  Actual: false
Expected: true
[  FAILED  ] transaction_manager.begin_rollback_transaction__1_resources_involved__expect_XA_OK (118 ms)
[ RUN      ] transaction_manager.begin_rollback_transaction__2_resources_involved__expect_XA_OK
unknown file: Failure
C++ exception with description "lookup: { service: .casual/transaction/state, correlation: nil, reply: }: TPENOENT" thrown in the test body.
[  FAILED  ] transaction_manager.begin_rollback_transaction__2_resources_involved__expect_XA_OK (119 ms)
[ RUN      ] transaction_manager.begin_commit_transaction__2_resources_involved__expect_two_phase_commit
/export/home/guo/casual/middleware/transaction/unittest/source/test_manager.cpp:672: Failure
Value of: local::begin() == common::code::tx::ok
  Actual: false
Expected: true
unknown file: Failure
C++ exception with description "lookup: { service: .casual/transaction/state, correlation: nil, reply: }: TPENOENT" thrown in the test body.
[  FAILED  ] transaction_manager.begin_commit_transaction__2_resources_involved__expect_two_phase_commit (121 ms)
[ RUN      ] transaction_manager.begin_transaction__2_resource_involved__owner_dies__expect_rollback
/export/home/guo/casual/middleware/transaction/unittest/source/test_manager.cpp:729: Failure
Value of: local::begin() == common::code::tx::ok
  Actual: false
Expected: true
[  FAILED  ] transaction_manager.begin_transaction__2_resource_involved__owner_dies__expect_rollback (128 ms)
```

I have not investigated further, but given that the number of failed tests vary a lot, the failures are likely to be timing related.

I disabled transaction_manager.* and transaction_manager_branch.* (that seems to fail with similar symptoms) and tests run better.

I still have to manually kill a process quite frequently. Seems as if "shutdown" of the domain at the end of the tests have problems. Usually this happens with the test  gateway_manager.advertise_b_to_B__call_b_via_A__simulate_A_get_the_same_call_message_again__loop_between_gateways__expect_error_reply

Killing the process:
`middleware/gateway/bin/casual-gateway-outbound-group
`
makes the test step run to completion with OK.

One of the tests that has caused me problems may have an "explanation" and potential fix:

I have "always" disabled one test (with GTEST_FILTER) in my test runs. `common_communication_ipc.send_multiplex_to_inbound__fill_the_ipc__and_cache_the_rest__sink_the_inbounds__expect_callback_invocation__and_empty_state_when_done 
`
This failure in this test seems to be related to a "failure" in the "fill the ipc" part.  The following code in the test seems to be the problem:
```
         algorithm::for_n< 10>( [&]()
         {
            for( auto& destination : destinations)
            {
               auto ipc = destination.connector().handle().ipc();
               coordinator.send( ipc, message, [ &errors]( auto&, auto&)
               {
                  ++errors;
               });
            }
         });
         
         // should hold state for the (part of) messages that did not get any room.
         EXPECT_TRUE( ! coordinator.empty());
```
If I change the 10 in the algorithm::for_n< 10> to 31 the test stops failing. With 30 or less it always fail. Perhaps the buffering defaults for the "socket" is different in Suse Linux (or at Bolagsverket). I do not know for sure what paramters affects this. Possibly the SNDBUF socket option. I have not tried to get the socket options to check the actual value.

**Comment by OlofGullnas** [comment]
More tests that fail in my single CPU Suse environment :-(. This is with latest 1.6/main as of today, commit 5457023d0d61cc129fea611a7ce2057424013fa1.   tag: 1.6.0-beta.47.

Seems as if timing is a factor as the set of failing tests varies. 

```
[----------] 4 tests from event_service_log
[ RUN      ] event_service_log.reopen_log_file
/export/home/guo/casual/middleware/event/unittest/source/service/test_log.cpp:81: Failure
Value of: ! common::unittest::file::fetch::until::content( log_file).empty()
  Actual: false
Expected: true
[  FAILED  ] event_service_log.reopen_log_file (6186 ms)
[ RUN      ] event_service_log.filter_exclusive
[       OK ] event_service_log.filter_exclusive (63 ms)
[ RUN      ] event_service_log.filter_inclusive
/export/home/guo/casual/middleware/event/unittest/source/service/test_log.cpp:158: Failure
Value of: ! common::unittest::file::fetch::until::content( log_file).empty()
  Actual: false
Expected: true
[  FAILED  ] event_service_log.filter_inclusive (6178 ms)
[ RUN      ] event_service_log.filter_inclusive_exclusive
/export/home/guo/casual/middleware/event/unittest/source/service/test_log.cpp:183: Failure
Value of: ! common::unittest::file::fetch::until::content(log_file).empty()
  Actual: false
Expected: true
[  FAILED  ] event_service_log.filter_inclusive_exclusive (6183 ms)
[----------] 4 tests from event_service_log (18610 ms total)
```
On my first run only event_service_log.filter_inclusive failed.
