### ISSUE TITLE
Reduce fuzz concerning nginx

### ISSUE THREAD

**Issue by albinsjolund** [casualcore/casual#22]
These are some thoughts about install_nginx.py etc

- Consider to use `--conf-path=nginx.conf` in order to find the nginx-configuration-file in the casual-domain-home-directory where you also probably will find domain-configuration
- Strongly consider to use `--error-log-path=nginx.log` and `--http-log-path=nginx.access.log` and `--pid-path=nginx.pid` (or such) in order to let nginx create log-files in same prefix-directory that probably is the same as casual-domain-home-directory and thus probably along casual.log and thus the user doesn’t have to manually create folders (since nginx doesn’t create them automatically)
- Strogly consider not to use `error_log  logs/debug.log  debug;` in default. nginx.conf (that foces user to manually create folders) (synch with `--error-log-path=nginx.log`) and this is also probably relevant with the configure directive `'--with-debug'`
- Consider removing all html-references in default nginx.conf (if someone wanna use the nginx-instance for presenting web-pages/applications another instance can be used of they can add it them self (this forces the user to copy mime-files etc)
- Strongly consider not to force users to invoke services with the uri-prefix casual (i.e. change `location /casual {      casual_pass;    }` to `location / {      casual_pass;    }` and thus change the casual_pass-plugin)

There’s also `--http-client-body-temp-path, --http-proxy-temp-path, --http-fastcgi-temp-path, --http-uwsgi-temp-path, --http-scgi-temp-path` as configuration parameters

The most important reason with this issue is to remove fuzz when doing a hello world and the second most important thing is to make things as coherant with casual and so little bloat as possible (i.e. less variables in configuration files, less files/folder all over in (a non coherant way with casual) the filesystem)

Done in 1.7:
- Strongly consider not to use `include       mime.types` in default nginx.conf (that forces the user to manually copy some files)
- Consider to remove the need for `CASUAL_BUILD_HOME`

Wont/cant do:
- Consider to not use `'--prefix=' + prefix` when configure and instead use `-p` in domain-configuration instead (I guess both can be used though) or at least not with the postfix `'/nginx'` in order start up where casual-domain-home is (also consider that `CASUAL_DOMAIN_HOME` might contain paths with spaces and such)
- Strongly consider to keep configure parameter `--with-cc-opt="-D FD_SETSIZE=[N]"` coordinated with `worker_connections` in the default/shipped nginx.conf (because nginx cannot be started with more connections that the built-in `FD_SETSIZE` (e.g. it is 64 by default on cygwin)

**Comment by lazan** [comment]
@ahhud How much of this is done?
