### ISSUE TITLE
service: untangle the lookup request handler from pending lookup 'processing'

### ISSUE THREAD

**Issue by AlbsAgren** [casualcore/casual#228]
The service manager reuses the same set of functions for pending lookups when receiving lookup requests as is used to process pending lookups when the state changes for other reasons, such as services being advertised or processes dying. Under some circumstances this causes the SM to send lookup replies that the caller isn't expecting. Ideally these "flows" should be separated to make this less error prone and easier to reason about.

**Comment by lazan** [comment]
@AlbsAgren I think this got a lot better in the SM-refactoring commits? Could you verify, and if it's still to complecting, update this issue more precisely what you think still should be done.

**Comment by AlbsAgren** [comment]
@lazan Yeah, I had a look at it and it feels a lot easier to follow. Closing this.
