### ISSUE TITLE
environment::set (reset) leaks memory on linux if the variable exists. 

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#275]
If we set the same environment variable multiple times, there will be memory leaks from _libc?_ . 

Generally we don't need to set environment variables per se, since most of it is passed to children via spawn. 

One thing we need to fix, is the _execution::set/reset_  that uses `CASUAL_EXECUTION_ID` variable to pass down to children. If this is what we want/need, we need to create it in spawn. Hence, only use the environment variable during initialisation.

It might be possible to remove the `set` all together.

**Comment by OlofGullnas** [comment]
On removing "-set-environment":
"Having the ability to set environment variables "from the outside" may be useful for application level things. Like controlling trace/debug/application level logging mechanisms in a running system. An alternative approach to do this may be to change the server configuration and restart servers/aliases.

**Comment by lazan** [comment]
Duplicate of #335
