### ISSUE TITLE
Fix entry web-page

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#295]

**Comment by lazan** [comment]
https://docs.google.com/document/d/130pNRxzofUdjYVa2dG9EkODKBDGkvMx9yKaKGUZnhKw/edit?usp=sharing

**Comment by OlofGullnas** [comment]
Vid en snabb genomläsning såg jag ett stavfel (kan finnas fler :-) )

I avsnittet om "Communication model".

"Communication between entities (processes) is done with messages passing."

'messages' ska nog vara 'message'.

Jag tycker det känns bättre att skriva "Communication between entities (processes) uses message passing.", men det är en petitess... Man kan antagligen skriva "Communication between entities (processes) uses messages." eller "... is message based" också. "is done with" känns i alla fall lite klumpigt.

I avsnittet om communication finns också:

"All communication is done asynchronously, hence there could be a lot of messages in flight within any given time."

Blir det inte bättre med:
"All communication is done asynchroously. There can be a lot of messages in flight at any given time."


I stycket:

"The most significant communication patterns are listed below, to provide an understanding of how casual works."

känns det bättre att byta plats på satserna...:

"To provide an understanding of how casual works, the most significant communication patterns are listed below."
 
(Man kanske ska använda "illustrated" eller "described" i stället för "listed".)
 
Borde det finnas något avsnitt/mening om API-er mellan service-kod och casual? Det är inte uppenbart för den okunnige att casual implementerar XATMI. Det finns iofs en referens till "XATMI" i "Specifications"  men för den som inte vet vad XATMI är så är det inte uppenbart att detta är ett API som används till och av tjänsterna. 

Man kanske skulle lägga till ett stycke i "What is casual" som säger att API till tjänsterna följer XATMI med tillägg för att också stödja "queued calls".

För den som letar efter något som stödjer XATMI är det centralt att casual gör det... 

Var skall denna entry page finnas? Är det lämpligt att skriva saker på sidan som gör att man potentiellt kan få träff på den om man söker på XATMI, Tuxedo, openUTM (en produkt från Fujitsu som också stödjer XATMI) eller någon av de övriga XATMI-implementationerna. Till exempel genom att skriva något i samband med XATMI-referensen som säger at det är en X/Open specifikation som implementerats av till exempel Oracle Tuxedo och Fujitsu openUTM och andra. Det kanske är principiellt tveksamt.
