### ISSUE TITLE
We need some kind of _pending_ timeout

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#296]
Service timeout defines how much time a service is allowed to consume, this does not include the time caller has been waiting for an instance to be idle.

We need some kind of _pending timeout_, that limit the time a caller waits for an idle instance.

**Comment by OlofGullnas** [comment]
Interesting issue :-) Lots of stuff to think about.

I have not studied how waiting for an available service provider works in any detail.

Timeout on the execution of a service is relatively well defined.

Timeout on waiting for one may be more complicated. What can/should be done if the same service is provided by multiple domains? I assume this is possible! If this is not the case things may be simpler.  Should a "failover" to a different domain be attempted if no server becomes available? I'm guessing that lookup request are only sent to one domain/service manager when multiple domains provide the service (which one is selected?). There is also the odd case of the local domain having the service, but other domains also provide it.

One possibility is to consider failover logic to be not needed/to complicated to be worth it.

**Comment by lazan** [comment]
The thing we've been discussing is a _pending timeout_. A duration that _operators_ sets depending on the topology, load and general characteristic of the deployment. 
Let's say we have one "global" duration set to 20s. If a service lookup is _pending_ (waiting for an instance to become idel) more than 20s we reply with "TPETIME" (or some other error), and error log this. Hence, we classify this as a deployment/scaling "error". 
This kind of solution is relatively easy to implement, since SM keep tracks of service timeout already.
