### ISSUE TITLE
confusing arguments to casual service --legend 

### ISSUE THREAD

**Issue by useless1024** [casualcore/casual#31]
To show the legend for 'list-services' you must write 'casual service --legend list-service' without the ending s.
'casual service --legend list-services' gives niether output nor errors.

**Comment by lazan** [comment]
The fix should be:
*  to still trigger on _--legend list-service_  (backward compatibility)
* remove _list-service_ from the --help and so on, all together.
* change to trigger on _--legend list-services_  of course.
* raise invalid argument if the value to --legend is not any of the ones that trigger legend
