### ISSUE TITLE
Assasinate should only have 100% lethal contract, or non lethal

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#344]
To be able to make correct decisions in SM we need to know if we've ordered a lethal contract or not. We need to know if we have to wait for an process::Exit event or not. 

Right now we have `terminate` that is not directly lethal. More like a "please exit when you can... or not". And this does not make sense in a "timeout context". Either one wants to let the server linger, or want it dead/stop process no matter what.

Hence we should have these "categories":
**linger:**
* linger
* interupt ( linger, but with a shoulder tap to maybe snap the server out of what it's doin) 

**lethal**
* kill
* quit ( kill with core, or other similar signals)

**Comment by OlofGullnas** [comment]
Is there a use for a lethal variant along the lines of "please terminate in an orderly fashion, but if you don't terminate in a reasonable time you will be killed". I.e. first a SIGTERM and then a SIGKILL if the process does not exit.
