### ISSUE TITLE
Add enqueue and dequeue services to casual-example-server

### ISSUE THREAD

**Issue by partickl** [casualcore/casual#348]
Should be possible to enqueue to or dequeue from a casual queue. Actual queue should be given as a command line parameter

**Comment by partickl** [comment]
Should we do this for 1.6 or 1.7? Imo this would be useful for 1.6 as well, to allow more tests.  Same goes for issue #349 i guess. What do you think @lazan ?

**Comment by lazan** [comment]
If we "need" this for performance tests, it would be practical to be able to run the same tests on 1.6 -> we can compare.
1.6 it is then.

**Comment by partickl** [comment]
create a new example server under `queue` instead
