### ISSUE TITLE
remove resource migrate functionality until we're "sure" what the use cases are

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#39]
Some resources (oracle db for example) support _migrate_, but still doesn't like to be migrated between processes. It should work without the migrate stuff, and does, so we don't use it until we're more confident what it means.

**Comment by OlofGullnas** [comment]
Related to this is the question:

- When shall xa_end with suspend (and matching resume) be called?
I think the cleanest strategy/principle is to call xa_end(suspend) for all RMs immediately before "blocking". This would be attempting to get the reply to a tpcall or tpacall, or in tprecv. This strategy assumes that called services will block and wait in xa_start (with join) in the cases where the RM cannot handle concurrent use of a transaction branch in multiple threads (in the sense the term threads is used in the XA specs). This would mean uniform handling for tpcall/tpacall and for conversational services.

Note that xa_start(resume) also may block in a way similar to xa_start(join). Can happen if another thread is using the RM and transaction branch. It then waits for an xa_end to release it.

Should most likely also suspend/resume in calls to tpsend. The tpsend() has a NOBLOCK option so it may block.

A general question is if suspend/resume should/need to be done in non-blocking calls to tpgetreply, tprecv or tpsend? Doing it in this case also is probably simpler than not doing it, and it may be required to handle unlikely "patological but possible" use cases.
