### ISSUE TITLE
Make sure to ensure mecanism for deallocate incoming buffers

### ISSUE THREAD

**Issue by KristianIvarsson** [casualcore/casual#411]
Checkout `casual::buffer::field::local::Buffer::m_inbound` (CFIELD) that have a mechnism that doesn't exists in CSTRING, COCTET and CORDER

**Comment by lazan** [comment]
@KristianIvarsson how important is this for `1.7`?

**Comment by KristianIvarsson** [comment]
Not any more important than for 1.6 @lazan 

These buffers are possibly not used, they are running `tpfree()` explicitly or none have noticed that they leak resources

I guess it could wait until a patch release

**Comment by lazan** [comment]
Assigned this to you. You got a few weeks to do it before 1.7 :)
