### ISSUE TITLE
update g++ on suse image

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#423]
```

/git/casual/casual/middleware/domain/source/discovery/state.cpp:95:20: error: ‘class std::optional<std::__cxx11::basic_string<char> >’ has no member named ‘transform’
   95 |                   .transform( []( auto value){ return common::chronology::from::string( value);})
      |                    ^~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-dangling-reference’ may have been intended to silence earlier diagnostics
```
If it doesn't understand `no-dangling-reference` it's pretty old, right?

**Comment by ahhud** [comment]
@lazan Well it was the latest gcc13 that existed for suse by the time I created the images. Perhaps there is a new version now.

**Comment by ahhud** [comment]
@lazan Or I have perhaps missed something about suse. I am checking now.

**Comment by ahhud** [comment]
@lazan Now it´s updated with latest g++13. All builds now in Suse but there is a testcase failing.
gateway_manager. A_B__pending_call_A_to_B__shutdown_B__send_implicit_update_to_A_outbound__expect_direct_reply__not_over_to_inbound
Perhaps some race condition, trying to build again.
Yep, now it's all green again. :-)
