### ISSUE TITLE
casual queue --list-instances is missing due to nameing mismatch

### ISSUE THREAD

**Issue by ahhud** [casualcore/casual#459]
When entering following removed CLI-command a hint is echoed:
```
$ casual gateway --list-queues
[casual:invalid_argument] --list-queues is removed - use casual queue --list-instances: invalid_argument
```
However casual queue --list-instances doesn't exist. The "correct" name is `casual queue --list-queue-instances`

For symmetry with casual service --list-services and casual service --list-instances I think casual queue also should use same naming i.e. casual queue --list-queues and casual queue --list-instances.

**Comment by lazan** [comment]
Perhaps... But `queue-manager` has _forwards_ and _queue-groups_.  I think `--list-instances` is to general, and user might expect to get _forward-instances_ also.

**Comment by lazan** [comment]
Hmm, maybe: `casual queue forward --list-instances`  and `casual queue --list-instances`. Thus:
We create a suboption `casual queue forward` and have all _forward_ options under it?
