### ISSUE TITLE
Signal upstream that a domain has new services/queues 

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#479]
We "need" to at least improve the following scenario
* domain A has service x with 2 instances
* domain B has service x
* domain C calls x loadbalanced between A and B
* the 2 instance cores/scales down in A
* domain C calls x only in B
* 2 instances scales up/restarts in A

`casual` will not call x in A again, unless some other thing trigger a "topology update" and C will "re" discover x in A

## solution

Either:
* when we notice that a service goes from > 0 instance  -> 0 instances -> > 0 instances , then we send topology update upstream
* More general, when new (local) services (and queues) are advertised.

We could accumulate this information for a long time (several seconds) before sending topology update upstream to reduce traffic. The objective is to eventually "heal".

**Comment by OlofGullnas** [comment]
A thought that struck me:
Any issues if/when services are "unadvertised" (as opposed to servers scaled down)?

I have not looked into this. It is possible that tjhis is handled by general mechanisms in Casual, but calling tpundvertise is not common...

**Comment by lazan** [comment]
We haven't got any proactive _signal upstream if a service is not available any more_. When a call get a `TPENOENT` the service is unadvertised from gateway.outbound, and no more calls to that service will be done over that connection. 
Hence, we've got a reactive handling. I don't think it's possible to implement a 100% proactive solution. You could do some sort of _if call got TPENOENT we reissue the call again and hope we get to a connection that has the service still_, but the complexity and the non-deterministic time it could take make it not likely that we'll proceed with.

**Comment by OlofGullnas** [comment]
Does that mean that when servers are scaled down to 0 instances, upstream is not notified about disappeared services? And that upstream callers of services may get a TPENOENT "glitch" when the load balancing algorithm send the call the "wrong way" until unadvertised from gateway outbound following a TPENOENT? 

I agree that getting 100% guarantee against glitches is difficult as there always may be unlucky timing cases, but should there be an ambition to reduce glitches? It is a bit unexpected  to get glitches if care is taken to scale down when the system is "idle" (or even "logically closed down"  upstream). 

I suspect that anything that casuses a new "discovery" to be initiated will cause "self healing"...

**Comment by lazan** [comment]
Our mantra is: Either fix the issue 100% or don't bother. We could of course make an exception...
