### ISSUE TITLE
Attributes on messages in queues must propagate with cli usage

### ISSUE THREAD

**Issue by ahhud** [casualcore/casual#49]
If one uses cli and either store a message on file and later enqueue it or to use casual-pipe to copy a message, the attributes on the message are lost. 
That information and possible more needs to be transfered as well and not only the payload.

**Comment by lazan** [comment]
I see two possible solutions for this:

1. use a separate message type for _queue message_ that includes the needed attributes. CLI consumer has to also dispatch on this message, of course... 
2. extend the current generic cli "payload" message with the needed attributes, and make them "optional"/sane defaults. 

\# 1 is more _correct_ I think, but \# 2 is, perhaps, more practical? We do  whatever seems to be the cheapest/easiest.

Hmm, on second thought, I think \# 1 is far better in the long run, and more in line with the rest...
