### ISSUE TITLE
Errors compiling with gcc-11/g++-11

### ISSUE THREAD

**Issue by OlofGullnas** [casualcore/casual#69]
I do not know which compiler versions are recommended/expected tor work for building Casual!

I used to have gcc-10/g++-10 as the system default compiler. Got a warning (treated as error) when compiling 
middleware/service/source/manager/handle.cpp. (This was with the feature/1.5/patch code stream)

This occured when building Casual without --debug. With --debug no warning/error occurred.

Some experiments gave that with gcc-9/g++-9 Casual built OK, so we switched to gcc-9/g++-9.

I also found that g++-11 gave a much improved warning message, compared to g++-10. 

As an experiment I have tried compiling feature/1.6/main (844ba23) with g++-11.  g++ -v displays the version string "gcc version 11.3.0 (SUSE Linux)".
Two files failed to compile:

**middleware/common/source/communication/socket.cpp**
Problem seems to be a missing #include <optional> in middleware/common/include/common/communication/socket.h. The header has a reference to std::optional but did not #include <optional>. Including this header was suggested by the compiler...

**middleware/service/source/manager/handle.cpp**
There is a code sequence:

>                       // check if some of the rest has _routes_
>                       for( auto& name : std::get< 1>( algorithm::sorted::intersection( message.content.services, reply.content.services)))
>                            if( auto found = algorithm::find( state.reverse_routes, name))
>                               reply.routes.services.emplace_back( found->first, found->second);
> 
implicated in the compiler message about a use of a possibly uninitialized variable _M_curreent deep down in the "range" code (in common/include/common/range.h:94:61, a begin() function returning m_first). Introducing a variable to hold the result of 
  algorithm::sorted::intersection( message.content.services, reply.content.services) 
and using this variable in the std::get< 1> in the for statement makes the warning/error go away.

To me this looks like a possible compiler issue. Or perhaps there is some obscure language rule around evaluation order or variable lifetimes that may cause a potential problem.

The unit tests runs OK except for 4  tests that I had to disable (GTEST_FILTER). The same tests also fail with g++-9. A few test cases also "hang". Most likely during "shutdown". Doing a kill to the casual process with the highest pid makes the hanging test complete without error.

**Comment by lazan** [comment]
I assume this issue will be solved implicitly by #73. Is this a resonable fix and timeline for you @OlofGullnas?

**Comment by OlofGullnas** [comment]
I/we have switched to g++-9/gcc-9 as the default compiler, so we do not have a problem.

If I really want to build with gcc-11 I have 2 small code changes sitting on a branch that seems to resolve the issues. An added include in one file, and a small reformulation introducing a local variable for the second problem.

I believe that the compile commands includes -std=c++17 so even with g++-11 it should be more or less C++17 (the language dialect) that is used.

I assume that the intention of #73 is to switch to -std=c++20. I do not know if it will expose incompatibilities, I suspect it will at least enable new language and library features.

**Comment by lazan** [comment]
I'm not sure if there will be ABI breakage. The compiler implementation can't break ABI unless it's stated by the standard, so it's pretty clear and deterministic to confirm. Either way, we build and deliver casual as a whole, so there shouldn't be any problems. Users are dependent (at least you) on the C-api anyway, and that's stable (rather, that's our intention).

**Comment by OlofGullnas** [comment]
(at least you):

Yes, we use the XATMI spec api (mainly the Cobol API, but also the C API directly and indirectly from the Cobol API.

Do you imply that Casual also has a "supported" C++ API? The file xatmi.cpp has really thin XATMI spec function implementations (extern "C") that call casual_* rutines in explicit/service.cpp. Those routines also have extern "C" linkage. Using the routines used by the casual_* functions seems to require a fair amount of knowledge about Casual internals. 

Or perhaps you refer to using the http mechanisms (or JCA/Java)

**Comment by OlofGullnas** [comment]
Fixed by PR #104
