### ISSUE TITLE
Remove Slack

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#84]
- [ ] remove "Slack webhooks" 
- [ ] Make sure users knows about Discord in Slack
- [ ] "freeze" Slack channels

**Comment by ahhud** [comment]
This has dependency to 1.5. As long as we are building 1.5-patches with jenkins the build process in jenkins will communicate with slack. The same is with casual-java which still uses jenkins.

**Comment by lazan** [comment]
> This has dependency to 1.5. As long as we are building 1.5-patches with jenkins the build process in jenkins will communicate with slack. The same is with casual-java which still uses jenkins.

Why cant we just remove the Slack communication? We still can monitor the progress in Jenkins? I don't understand... Please enlighten me.

**Comment by lazan** [comment]
> This has dependency to 1.5. As long as we are building 1.5-patches with jenkins the build process in jenkins will communicate with slack. The same is with casual-java which still uses jenkins.

On second thought, the problem is not number of messages in slack any more... Our pinned messages that guide lost users to Discord will still be lost... Hmm, ok, your call. 
I still like to understand why you don't want to remove the Slack communication though 😄 ...

**Comment by ahhud** [comment]
Exactly where in my statement does it say that I dont **want** to remove Slack communication?
I have removed Slack everywhere where I can. But I wont even touch Jenkinsfiles with a 10 foot pole. But by all means, next time you do a patch on 1.5 remove the slack statements in the Jenkinsfile.

**Comment by lazan** [comment]
> Exactly where in my statement does it say that I dont **want** to remove Slack communication?

... on 1.5, was may conclusion. Which in practice means a long time...

**Comment by lazan** [comment]
Let it die by it self...
