### ISSUE TITLE
casual-queue-forward occasionally hangs on shutdown

### ISSUE THREAD

**Issue by AlbsAgren** [casualcore/casual#98]
Potentially caused by the TM not sending an error reply to the forward after it fails to send a rollback_request to an outbound-grup. This would cause the forward to be stuck with an instance it cannot get rid of even though the transaction has been rolled back elsewhere.

**Comment by kentsoderlind** [comment]
I have seen this happen when the outbound group loses connection to the remote instance. The forward gets stuck and becomes inactive and won't go down cleanly even if the remote group gets a new connection.
